### ISSUE TITLE
Feature request: poseidon 2 implementation

### ISSUE THREAD

**Issue by mrain** [EspressoSystems/jellyfish#704]
For VID

## References

- Poseidon2 [paper](https://eprint.iacr.org/2023/323)
- plonky3 reference [implementation ](https://github.com/Plonky3/Plonky3/blob/main/poseidon2/)
- zkhash [rust implementation](https://github.com/HorizenLabs/poseidon2/blob/main/plain_implementations/src/poseidon2/poseidon2.rs) that we might directly use or modify on top.

**Comment by alxiong** [comment]
After reading through both plonky3 and zkhash's implementations, here is a summary: 
- zkhash is written by the author of P2 paper, using arkworks backend, can be directly used by us, (except we need to extend a few trait impl for them, e.g. `HasherDigest` since we can't directly impl `Digest` for them)
- plonky3 uses their only `FieldAlgebra` internally defined
- zkhash's impl is still academic code, less actively maintained, code structure is okay but not great, many prunable logic (as I assume they modify on top of their existing poseidon impl, there are some legacy baggage) 
- plonky3's impl is clean, modular, and performant. We should follow their impl. 

Actions:
1. directly use zkhash to make Poseidon2 MT available in jellyfish first
2. I will implement our own, following more closely with plonky3's structure, inside jellyfish, then drop-in replace zkhash

**Comment by alxiong** [comment]
Once #708 is merged, we have some follow-up (in descending priority)

- Change `jf_merkle_tree`'s import from `path = "../poseidon2"` to a tag after we add a tag to a commit on main
- Add a CRHF for poseidon2
- Implement circuit for P2
